services:
  app:
    build: .
    container_name: cachet-app
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=${APP_URL}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cachet
      - DB_USERNAME=cachet
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHET_TRUSTED_PROXIES=*
      - FORCE_MIGRATION=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - cachet_storage:/var/www/html/storage
      - nginx_logs:/var/log/ngin

  db:
    image: mysql:8.0
    container_name: cachet-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=cachet
      - MYSQL_USER=cachet
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

volumes:
  cachet_storage:
    driver: local
  nginx_logs:
    driver: local
